### ISSUE TITLE
Schéma de la base de données

### ISSUE THREAD

**Issue by gausoft** [Togodevelopers/Api_commune_Togo#5]
J'aimerais qu'on se penche un peu sur une structure de la base de donnés.
Apparement le système de subdivision administrative dans le grand Lomé est different de celui du reste du pays.
Voici une ébauche de ce que j'ai essayé de modéliser : 

- [Togo Municipalites Diagram](https://drive.google.com/file/d/17-so_QJM9YPwCLnu1b_8_qdCROJFwNF-/view?usp=sharing)

## Note
Je ne cerne pas le lien entre Commune et Préfecture

**Comment by lawalalao** [comment]
Okay je vais voir cela de près et faire un retour . Merci @Gausoft

**Comment by comraderoyce** [comment]
> Je ne cerne pas le lien entre Commune et Préfecture

I believe the commune is the base unit now. Prefecture is the containing unit of the communes (Golfe, Lacs, etc.). After that is the Regions (Maritime, Plateaux, etc.). After is Togo itself (should add a structure in the db for this).

Unfortunately there is a lot of outdated material online that uses the old pre-2019 prefecture information that is slightly different from the new set up with the communes. 

Some more suggestions: 

- Add additional level for "Pays" above "Regions"
- Direigent is for the mayor or similar? If so that's good and could link this at the commune level to start.
- Should add some other structures for mayor, ministers, budget, etc. on the commune level
- Should add some description field to the "Address" structure. This way can add "rue xyz en face de pharmacie xyz" or similar description of the location.

**Comment by comraderoyce** [comment]
> subdivision administrative dans le grand Lomé

also note that the Grande Lomé is the set of communes listed but not sure how much otherwise their administrative structure is actually different on the commune level.

**Comment by gausoft** [comment]
Ok, thanks
